# Generated by Django 4.2.5 on 2023-10-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
