# Generated by Django 4.2.5 on 2023-10-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_options_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaprod',
            options={'verbose_name': 'CategoriaCursos', 'verbose_name_plural': 'CategoriasCursos'},
        ),
    ]
