# Generated by Django 4.2.5 on 2023-10-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_categoriaprod_options_alter_producto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='tienda'),
        ),
    ]
