# Generated by Django 4.2.5 on 2023-10-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='Perfil',
        ),
    ]
