# Generated by Django 4.2.5 on 2023-10-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_rename_location_user_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Ubicacion',
            field=models.CharField(default=5, max_length=60),
            preserve_default=False,
        ),
    ]
