# Generated by Django 4.2.5 on 2023-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_alter_user_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Perfil',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Ubicacion',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
