# Generated by Django 4.2.5 on 2023-10-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_rename_perfil_user_picture_remove_user_ubicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='Perfil',
        ),
    ]
