# Generated by Django 4.2.5 on 2023-10-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0008_rename_bio_user_biografia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Foto_de_perfil',
            new_name='Fotodeperfil',
        ),
    ]
