# Generated by Django 4.2.5 on 2023-10-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0010_rename_fotodeperfil_user_fotoperfil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Biografia',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='DPI',
            new_name='dpi',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FechaNacimiento',
            new_name='fechadenacimiento',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FotoPerfil',
            new_name='fotoperfil',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Ubicacion',
            new_name='ubicacion',
        ),
    ]
