# Generated by Django 4.2.5 on 2023-10-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0011_rename_biografia_user_biografia_rename_dpi_user_dpi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='biografia',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ubicacion',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fotoperfil',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fechadenacimiento',
        ),
    ]
