# Generated by Django 4.2.5 on 2023-10-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0012_rename_biografia_user_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='Perfil',
        ),
    ]
