# Generated by Django 4.2.5 on 2023-10-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0015_rename_picture_user_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='perfil',
            new_name='picture',
        ),
    ]
